version: '3.7'

volumes:
  cargo-cache:

services:
  ckb:
    build: 
      context: layer1
    ports: 
      - 8114:8114
    volumes:
      - ../ckb-data/:/code
    # logging:
    #   driver: "none"
    # environment:
    #   - SE_OPTS="log ckb-log.txt"
    
  # ckb-indexer:
  #   build: 
  #     context: ckb-indexer
  #   ports:
  #     - 8116:8116
  #   network_mode: 'bridge'
  #   volumes:
  #     - ../indexer-data/:/code
  #   depends_on:
  #     - ckb
    

#  compile-lock: 
#    build: 
#      context: compile-lock
#    volumes: 
#      - common_file:/code

#  lumos-config:
#    build: 
#      context: lumos-config
#    networks: 
#      - layer1
#      - layer2
#    volumes: 
#      - common_file:/code/lumos-config-generator
#    depends_on: 
#      - chain
 
  postgres:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: lumos
      POSTGRES_PASSWORD: password
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ../web3-sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

#   lumos:
#     image: retricsu/gowoken-build_dev:ubuntu20
#     volumes:
#       - ../:/code
#     command: bash /code/lumos_entrypoint.sh
#     depends_on: 
#       - postgres

  godwoken:
    image: retricsu/gowoken-build_dev:ubuntu20
    volumes:
      - ../:/code
      - cargo-cache:/usr/local/cargo
      - ../ckb-cli-data:/root/.ckb-cli
    environment: 
      FORCH_GODWOKEN_REDEPLOY: ${FORCH_GODWOKEN_REDEPLOY}
    command: bash /code/godwoken_entrypoint.sh
    ports: 
      - 8116:8116
      - 8119:8119
    depends_on: 
      - ckb
    #  - lumos
    #  - ckb-indexer
      - postgres

  polyjuice:
    image: retricsu/gowoken-build_dev:ubuntu20
    volumes:
      - ../:/code
    command: bash /code/polyjuice_entrypoint.sh
    ports:
      - 6101:6101
      - 6100:6100
    depends_on:
      - ckb
    #  - lumos
      - postgres
    
  web3:
    image: node:14
    volumes: 
      - ../:/code
    command: bash /code/web3_entrypoint.sh
    environment: 
       PORT: 8024
    ports:
      - 8024:8024
    depends_on: 
      - postgres
      - godwoken
  
  gen-godwoken-schema:
    image: retricsu/gowoken-build_dev:ubuntu20
    profiles: ["cli-only"]
    volumes: 
      - ../:/code
    command: bash /code/docker/gen-godwoken-schema/entrypoint.sh
    
