# {workspaceDir}/docker/docker-compose.yml
version: '3.8'

volumes:
  cargo-cache:

services:
  godwoken-all-in-one:
    image: nervos/godwoken-prebuilds:v0.2.0-rc2
    ports:
    - 8114:8114 # CKB EXPOSE 8114 8115?
    volumes:
    - ../ckb-data/:/ckb-data
    - ./layer1/entrypoint.sh:/entrypoint/ckb.sh
    environment:
    # env of layer 1: TODO: use env_file https://docs.docker.com/compose/compose-file/compose-file-v3/#env_file
    - CKB_CHAIN=dev
    - BA_ARG=0x43d509d97f26007a285f39241cffcd411157196c
    - BA_CODE_HASH=0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8
    - BA_HASH_TYPE=type
    - BA_MESSAGE=0x1234
    # - SE_OPTS="log ckb-log.txt"
    # env of layer 2:
    # logging:
      # driver: "none"
    command: ["sh", "/entrypoint/ckb.sh"]
    
  # ckb-indexer:
  #   build: 
  #     context: ckb-indexer
  #   ports:
  #     - 8116:8116
  #   network_mode: 'bridge'
  #   volumes:
  #     - ../indexer-data/:/code
  #   depends_on:
  #     - ckb
    

#  compile-lock: 
#    build: 
#      context: compile-lock
#    volumes: 
#      - common_file:/code

#  lumos-config:
#    build: 
#      context: lumos-config
#    networks: 
#      - layer1
#      - layer2
#    volumes: 
#      - common_file:/code/lumos-config-generator
#    depends_on: 
#      - chain
 
  postgres:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: lumos
      POSTGRES_PASSWORD: password
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ../web3-sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

#   lumos:
#     image: retricsu/gowoken-build_dev:ubuntu20
#     volumes:
#       - ../:/code
#     command: bash /code/lumos_entrypoint.sh
#     depends_on: 
#       - postgres

  godwoken:
    image: retricsu/gowoken-build_dev:ubuntu20
    volumes:
      - ../:/code
      - cargo-cache:/usr/local/cargo
      - ../ckb-cli-data:/root/.ckb-cli
    environment: 
      FORCH_GODWOKEN_REDEPLOY: ${FORCH_GODWOKEN_REDEPLOY}
    command: bash /code/godwoken_entrypoint.sh
    ports: 
      - 8116:8116
      - 8119:8119
    depends_on: 
      - godwoken-all-in-one
    #  - lumos
    #  - ckb-indexer
      - postgres

  polyjuice:
    image: retricsu/gowoken-build_dev:ubuntu20
    volumes:
      - ../:/code
    command: bash /code/polyjuice_entrypoint.sh
    ports:
      - 6101:6101
      - 6100:6100
    depends_on:
      - godwoken-all-in-one
    #  - lumos
      - postgres
    
  web3:
    image: node:14
    volumes: 
      - ../:/code
    command: bash /code/web3_entrypoint.sh
    environment: 
       PORT: 8024
    ports:
      - 8024:8024
    depends_on: 
      - postgres
      - godwoken
  
  gen-godwoken-schema:
    image: retricsu/gowoken-build_dev:ubuntu20
    profiles: ["cli-only"]
    volumes: 
      - ../:/code
    command: bash /code/docker/gen-godwoken-schema/entrypoint.sh
    
